name: 'Locate vcvarsall and Setup Environment'
description: 'Locates vcvarsall.bat, sets up the environment, and handles PATH updates.'
inputs:
  architecture:
    description: 'Target architecture (x64 or x86)'
    required: true
    default: 'x64'
runs:
  using: "composite"
  steps:
    - name: Locate vcvarsall and update environment
      id: locate-vcvarsall
      shell: cmd
      run: |
        call ${{ github.action_path }}\locate_vcvarsall.bat ${{ inputs.architecture }}