##### start trigger Don't edit it manually, Please do edit set-trigger-rules.py ####
### please do rerun set-trigger-rules.py ###
trigger:
  branches:
    include:
    - main
    - rel-*
  paths:
    exclude:
    - docs/**
    - README.md
    - CONTRIBUTING.md
    - BUILD.md
pr:
  branches:
    include:
    - main
    - rel-*
  paths:
    exclude:
    - docs/**
    - README.md
    - CONTRIBUTING.md
    - BUILD.md
#### end trigger ####

parameters:
- name: NpmPublish
  displayName: 'NPM packages publish configuration'
  type: string
  values:
  - 'nightly (@dev)'
  - 'release candidate (@rc)'
  - 'production (@latest)'
  - 'custom'
  default: 'nightly (@dev)'

variables:
  # pipeline should define the following variables
  #   ExtraBuildArgs
  #   VersionSuffix

  ${{ if eq(parameters.NpmPublish, 'nightly (@dev)') }}:
    NpmPackagingMode: 'dev'
  ${{ if eq(parameters.NpmPublish, 'release candidate (@rc)') }}:
    NpmPackagingMode: 'rc'
  ${{ if eq(parameters.NpmPublish, 'production (@latest)') }}:
    NpmPackagingMode: 'release'
  ${{ if eq(parameters.NpmPublish, 'custom') }}:
    NpmPackagingMode: '$(VersionSuffix)'

stages:
- stage: check_GPU_info
  jobs:
  - job: nvidia_smi
    pool:
      name: onnxruntime-Win2022-webgpu-A10
    steps:
    - script: |
        nvidia-smi
      displayName: 'Check GPU info'
