parameters:
  - name: QnnSDKVersion
    type: string
    default: '2.27.0.240926'

steps:
  - script: |
      azcopy cp --recursive https://lotusscus.blob.core.windows.net/models/qnnsdk/qnn-v${{ parameters.QnnSDKVersion }} $(Agent.TempDirectory)
    displayName: 'Download QNN SDK v${{ parameters.QnnSDKVersion }}'

  - bash: |
      echo "##vso[task.setvariable variable=QnnSDKRootDir]$(Agent.TempDirectory)/qnn-v${{ parameters.QnnSDKVersion }}"
    displayName: Set QnnSDKRootDir

  - script: |
      echo $(QnnSDKRootDir)
    displayName: 'Print QnnSDKRootDir after downloading QNN SDK'

  - script: |
      set -x
      sdk_file="$(QnnSDKRootDir)/sdk.yaml"
      qnn_sdk_version=$(grep '^version:' "$sdk_file" | head -n 1 | cut -d':' -f2 | xargs | cut -d'.' -f1-3)
      if [[ -n "$qnn_sdk_version" ]]; then
        # Do not output ##vso[] commands with `set -x` or they may be parsed again and include a trailing quote.
        set +x
        echo "##vso[task.setvariable variable=QnnSDKExtractedVersion ;isOutput=true]$qnn_sdk_version"
      else
        echo "Version not found in sdk.yaml."
        exit 1
      fi
    displayName: Get_QnnSDKExtractedVersion based on sdk.yaml
    name: Get_QnnSDKExtractedVersion
  - bash: |
      echo "QnnSDKExtractedVersion =$(Get_QnnSDKExtractedVersion.QnnSDKExtractedVersion )"
    displayName: 'Print QnnSDKExtractedVersion  after extracting from sdk.yaml'

  - script: |
      azcopy cp --recursive 'https://lotusscus.blob.core.windows.net/models/qnnsdk/Qualcomm AI Hub Proprietary License.pdf' $(QnnSDKRootDir)
    displayName: 'Download Qualcomm AI Hub license'

  - script: |
      ls -al $(QnnSDKRootDir)
    displayName: 'Print contents of QNN SDK'
