parameters:
  - name: QnnSDKVersion
    type: string
    default: '2.27.0.240926'

steps:
  - script: |
      azcopy cp --recursive https://lotusscus.blob.core.windows.net/models/qnnsdk/qnn-v${{ parameters.QnnSDKVersion }} $(Agent.TempDirectory)
    displayName: 'Download QNN SDK v${{ parameters.QnnSDKVersion }}'

  - bash: |
      echo "##vso[task.setvariable variable=QnnSDKRootDir]$(Agent.TempDirectory)/qnn-v${{ parameters.QnnSDKVersion }}"
    displayName: Set QnnSDKRootDir

  - script: |
      echo $(QnnSDKRootDir)
    displayName: 'Print QnnSDKRootDir after downloading QNN SDK'

  - script: |
      set -x
      sdk_file="$(QnnSDKRootDir)/sdk.yaml"
      parsed_qnn_sdk_version=$(grep '^version:' "$sdk_file" | head -n 1 | cut -d':' -f2 | xargs | cut -d'.' -f1-3)

      if [[ -z "$parsed_qnn_sdk_version" ]]; then
        echo "QNN version not found in sdk.yaml."
        exit 1
      fi

      # Compare provided version with version from sdk.yaml (compare only major.minor.patch)
      if [[ "$sdk_yaml_version" == "${QnnSDKVersion%%.*.*.*}" ]]; then
        echo "Success: QnnSDKVersion matches sdk.yaml version ($parsed_qnn_sdk_version)."
      else
        echo "Error: QnnSDKVersion ($QnnSDKVersion) does not match sdk.yaml version ($parsed_qnn_sdk_version) in the QNN SDK directory"
        exit 1
      fi
    displayName: "Sanity Check: QnnSDKVersion vs sdk.yaml version"

  - script: |
      azcopy cp --recursive 'https://lotusscus.blob.core.windows.net/models/qnnsdk/Qualcomm AI Hub Proprietary License.pdf' $(QnnSDKRootDir)
    displayName: 'Download Qualcomm AI Hub license'

  - script: |
      ls -al $(QnnSDKRootDir)
    displayName: 'Print contents of QNN SDK'
